fixed new check tag

diff --git a/.github/workflows/main-pr-wf.yaml b/.github/workflows/main-pr-wf.yaml
--- a/.github/workflows/main-pr-wf.yaml
+++ b/.github/workflows/main-pr-wf.yaml
@@ -8,25 +8,29 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
       - name: Get version
         run: BASEDIR=$(pwd) ./tools/get_version.sh
       - name: Set version
         run: BASEDIR=$(pwd) ./tools/get_version.sh >> $GITHUB_ENV
-      - name: Check if tag exist.
-        shell: bash
+      - name: Check if tag exist 2
         run: |
-          git tag ${{ env.VERSION }}
-          if [ $? -ne 0 ]
+          TAG=$(git tag -l ${{ env.VERSION }})
+          if [ -n "$TAG" ]
           then
-            core.setFailed('This multiomix version tag already exists in repository')
-          fi
+            echo "::error::This bio-api version tag ($TAG) already exists in repository."
+            exit 1
+          fi 
 
   version-check-docker:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
       - name: Get version
         run: BASEDIR=$(pwd) ./tools/get_version.sh
       - name: Set version
