New Celery CI integration (#37)
* Starting with new celery image creation pipeline@

* Celery docker image creation in WF

- Docker file and docker ignore for celery worker.
- Deleted python tests and settings for ci.
- Added version tag check.
- Base image upgrated to python:3.8.17-slim-bullseye

* Fix Docker file to be taken in WF

* fixed new check tag

diff --git a/.github/workflows/main-pr-wf.yaml b/.github/workflows/main-pr-wf.yaml
--- a/.github/workflows/main-pr-wf.yaml
+++ b/.github/workflows/main-pr-wf.yaml
@@ -4,11 +4,33 @@ on:
     branches:
       - "main"
 jobs:
-  version-check:
+  version-check-repo:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Get version
+        run: BASEDIR=$(pwd) ./tools/get_version.sh
+      - name: Set version
+        run: BASEDIR=$(pwd) ./tools/get_version.sh >> $GITHUB_ENV
+      - name: Check if tag exist 2
+        run: |
+          TAG=$(git tag -l ${{ env.VERSION }})
+          if [ -n "$TAG" ]
+          then
+            echo "::error::This bio-api version tag ($TAG) already exists in repository."
+            exit 1
+          fi 
+
+  version-check-docker:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
       - name: Get version
         run: BASEDIR=$(pwd) ./tools/get_version.sh
       - name: Set version
